export const CHANGE_TYPE = 'AUTH/CHANGE_TYPE'
export const SUBMIT_BUTTON = 'AUTH/SUBMIT_BUTTON'
export const SOMETHING_ERROR = 'AUTH/SOMETHING_ERROR'
export const CHANGE_INPUT_EMAIL = 'AUTH/CHANGE_INPUT_EMAIL'
export const CHANGE_INPUT_PASSWORD = 'AUTH/CHANGE_INPUT_PASSWORD'
export const RESET_INPUTS = 'AUTH/RESET_INPUTS'
export const GET_TOKEN = 'AUTH/GET_TOKEN'

export const SUBMIT_CLICK_BUTTON = 'HOME/SUBMIT_CLICK_BUTTON'
export const SEARCH_VALUE = 'HOME/SEARCH_VALUE'

export const TAKE_DATA = 'SEARCH/TAKE_DATA'
export const CLEAR_DATA = 'SEARCH/CLEAR_DATA'